### ISSUE TITLE
CLANNAD FV无法hook

### ISSUE THREAD

**Issue by Stillily** [HIllya51/LunaHook#117]
### vndb link/id

CLANNAD FV

### Game resource 游戏资源

https://drive.google.com/file/d/1c-sVKW5rLlOaKl_WoPXZutgAVfAshRPB/view?usp=drive_link

### screenshot 截图

![WeChat截图_20240813090015](https://github.com/user-attachments/assets/e7c848b0-3a1a-4732-8e18-c28457120105)

使用LE启动后选择游戏的exe报错

H:\CLANNAD FV\REALLIVE.EXE
['CLANNAD プロローグ', 'CLANNAD FV']
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ~~~~~~~~~^^^^^
KeyError: 'vid'
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ~~~~~~~~~^^^^^
KeyError: 'vid'
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ~~~~~~~~~^^^^^
KeyError: 'vid'
POST vn {'filters': ['search', '=', 'CLANNAD プロローグ'], 'fields': 'id', 'sort': 'searchrank'}
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 315, in getidbytitle
    vid = getidbytitle_(self.proxy, title)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 84, in getidbytitle_
    vid = getvidbytitle_vn(proxy, title)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 66, in getvidbytitle_vn
    return js["results"][0]["id"]
           ~~~~~~~~~~~~~^^^
IndexError: list index out of range
POST vn {'filters': ['search', '=', 'CLANNAD プロローグ'], 'fields': 'id', 'sort': 'searchrank'}
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 315, in getidbytitle
    vid = getidbytitle_(self.proxy, title)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 84, in getidbytitle_
    vid = getvidbytitle_vn(proxy, title)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 66, in getvidbytitle_vn
    return js["results"][0]["id"]
           ~~~~~~~~~~~~~^^^
IndexError: list index out of range
POST vn {'filters': ['search', '=', 'CLANNAD FV'], 'fields': 'id', 'sort': 'searchrank'}
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 315, in getidbytitle
    vid = getidbytitle_(self.proxy, title)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 84, in getidbytitle_
    vid = getvidbytitle_vn(proxy, title)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\vndb.py", line 66, in getvidbytitle_vn
    return js["results"][0]["id"]
           ~~~~~~~~~~~~~^^^
IndexError: list index out of range
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\bangumi.py", line 164, in getidbytitle
    response = self.proxysession.get(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 436, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\commonbase.py", line 20, in request
    return super().request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 413, in request
    response = requester.request(
               ^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 230, in request
    return self.request_impl(
           ^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 240, in request_impl
    self._perform(curl)
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 93, in _perform
    self.raise_for_status()
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 67, in raise_for_status
    MaybeRaiseException(self.last_error)
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\libcurl.py", line 343, in MaybeRaiseException
    raise e
network.libcurl.libcurl.CURLException: URL_MALFORMAT: URL using bad/illegal format or missing URL
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\bangumi.py", line 164, in getidbytitle
    response = self.proxysession.get(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 436, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\commonbase.py", line 20, in request
    return super().request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 413, in request
    response = requester.request(
               ^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 230, in request
    return self.request_impl(
           ^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 240, in request_impl
    self._perform(curl)
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 93, in _perform
    self.raise_for_status()
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 67, in raise_for_status
    MaybeRaiseException(self.last_error)
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\libcurl.py", line 343, in MaybeRaiseException
    raise e
network.libcurl.libcurl.CURLException: URL_MALFORMAT: URL using bad/illegal format or missing URL
Traceback (most recent call last):
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\utils.py", line 213, in trysearchforid_1
    vid = targetmod[key].getidbytitle(arg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\metadata\bangumi.py", line 164, in getidbytitle
    response = self.proxysession.get(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 436, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\myutils\commonbase.py", line 20, in request
    return super().request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 413, in request
    response = requester.request(
               ^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\requests.py", line 230, in request
    return self.request_impl(
           ^^^^^^^^^^^^^^^^^^
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 240, in request_impl
    self._perform(curl)
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 93, in _perform
    self.raise_for_status()
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\requester.py", line 67, in raise_for_status
    MaybeRaiseException(self.last_error)
  File "H:\translate_out\LunaTranslator\LunaTranslator\network\libcurl\libcurl.py", line 343, in MaybeRaiseException
    raise e
network.libcurl.libcurl.CURLException: URL_MALFORMAT: URL using bad/illegal format or missing URL

**Comment by HIllya51** [comment]
下载链接无效

**Comment by Stillily** [comment]
权限更好了，链接是一样的

**Comment by HIllya51** [comment]
![屏幕截图 2024-08-13 110734](https://github.com/user-attachments/assets/0e8adf32-f746-412d-8954-2a5aa24a1cb3)

搞毛线，浪费我时间。

**Comment by Stillily** [comment]
我也试出来能识别了，把LE的管理员勾选，伪造UI取消勾选后
